run:
  timeout: 10m

linters:
  disable-all: true
  enable:
    - deadcode
    - gofmt
    - gosimple
    - ineffassign
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - goconst
    - staticcheck
    - errcheck

linters-settings:
  goconst:
    # minimal length of string constant, 3 by default
    min-len: 5
    # minimal occurrences count to trigger, 3 by default
    min-occurrences: 5
