{
 "title": "Items",
 "tags": [ "mSupply" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "store",
    "label": "Store",
    "query": " select distinct n.name from name n join name_store_join nsj on n.id=nsj.name_id where n.type='store' and nsj.inactive=false order by n.name"
   },
   {
    "name": "item",
    "label": "Item",
    "query": " select item_name from item order by item_name;"
   },
   { "name": "ven", "label": "VEN", "query": "V,E,N" }
  ]
 },
 "panels": [
  {
   "title": "Stock Status by Item",
   "type": "grafana-region-map-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select current_date as \"time\", store, item, value, region.description as \"region\", geojson.\"data\" as \"geojson\"\nfrom (\n\tselect store.name as store, item.item_name as item, store.id as store_id, item.id as item_id, store.name_id as name_id, avg(a.value) AS value\n\tfrom aggregator a\n\tjoin store on a.storeid = store.id and store.disabled = false\n\tjoin item on a.itemid = item.id\n\tjoin item_store_join isj on a.storeid = isj.store_id and a.itemid = isj.item_id and isj.inactive = false\n\twhere a.dataelement = 'mos' and item.ven_category in ([[ven]])\n\tgroup by 1,2,3,4,5\t\n) as a\n\tjoin \"name\" as n on name_id=n.id\n\tjoin name_category1_level1 as region on n.category1_id = region.id\n\tjoin geojson on region.id = geojson.id\nwhere item = [[item]] and store in ([[store]])\norder by region.description;"
    }
   ]
  },
  {
   "title": "Item Value",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select store, SUM(value) as value\nfrom \n(\n\tselect item.item_name as \"item\", store.name as \"store\", item_line.cost_price*item_line.quantity as value\n\tfrom item\n\tjoin item_line on item.ID = item_line.item_id\n\tjoin item_store_join isj on item.id = isj.item_id\n\tjoin store on isj.store_id = store.id\n\twhere isj.inactive = false\n\t\tand isj.non_stock = false\n\t\tand item.type_of = 'general'\n\t\tand item_line.quantity>0\n\t\tand item_line.ID <> ''\n\t\tand item.ven_category in ([[ven]])\n) as a\nwhere a.item = [[item]] and store in ([[store]])\ngroup by store\n"
    }
   ]
  },
  {
   "title": "Suppliers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(supplier) from name\nwhere supplier = true"
    }
   ]
  },
  {
   "title": "Suggested POs",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(status) from purchase_order\nwhere status = 'sg'\n"
    }
   ]
  },
  {
   "title": "Suggested invoices",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT count(type) from transact\nwhere status = 'sg'"
    }
   ]
  },
  {
   "title": "Transactions per store by type",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT * FROM crosstab( 'select name, type, count(type) from transact\njoin store on store.id = transact.store_ID\ngroup by store.name, type \norder by 1, 2') \nAS ct(name varchar, ci bigint, si bigint, sr bigint, cc bigint, sc bigint) "
    }
   ]
  },
  {
   "title": "Customers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(customer) from name\nwhere customer = true"
    }
   ]
  }
 ]
}