{
 "title": "Overview",
 "tags": [ "mSupply" ],
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "store",
    "label": "Store",
    "query": "select de.name from data_elements de join user_elements ue on de.uid = ue.element_uid where de.type = 'store'  order by de.name"
   },
   {
    "name": "item",
    "label": "Item",
    "query": "select de.name from data_elements de where de.type = 'item' order by de.name"
   },
   { "name": "region", "label": "Region" }
  ]
 },
 "panels": [
  {
   "title": "Total Stock Value",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select current_date as time, sum(dv.value)\nfrom data_values dv\njoin data_value_elements dve on dv.uid = dve.data_value_uid\njoin data_elements store on dve.data_element_uid = store.uid and store.type = 'store'\nwhere dv.type='totalValue' and store.name in ([[store]]) group by 1;\n"
    }
   ]
  },
  {
   "title": "Stock Value by Store",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT CURRENT_DATE AS \"time\",\n    store.name AS \"metric\",\n    sum(stock.value) \n   FROM data_values stock\n   join data_value_elements stock_join on stock.uid = stock_join.data_value_uid\n     JOIN data_elements store ON stock_join.data_element_uid::text = store.uid::text\n  WHERE stock.type::text = 'stockValue'::text AND store.name IN ($store)\n  group by 1, 2;"
    }
   ]
  },
  {
   "title": "Months of Stock by Region",
   "type": "grafana-region-map-panel",
   "description": "Shows the average months of stock available across regions. The selection can be filtered by selecting one or more stores from the Store drop down at the top of the page.",
   "gridPos": { "h": 11, "w": 13, "x": 10, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\",\n  region,\n  geojson,\n  avg(value) AS \"value\"\nFROM region_mos\nwhere store in ([[store]])\nGROUP BY 1,2,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stock Status",
   "type": "grafana-piechart-panel",
   "description": "Shows average months of stock available for the store(s) and item(s) that you select above.\nUnder is less than three months, Over is more than six and Normal is between three and six months.",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select CURRENT_DATE AS \"time\", case when value = 0 then 'zero' when value > 6 then 'over (>6)' when value < 3 then 'under (<3)' else 'normal' end as metric, count(*) as count \nfrom\n(\nselect avg(value) as value\nfrom\n(\n   SELECT item.name AS item,\n    mos.value\n   FROM data_values mos\n   join data_value_elements store_join on mos.uid = store_join.data_value_uid \n     JOIN data_elements store ON store_join.data_element_uid = store.uid and store.type = 'store'\n   join data_value_elements item_join on mos.uid = item_join.data_value_uid \n     JOIN data_elements item ON item_join.data_element_uid::text = item.uid::text and item.type = 'item'\n  WHERE mos.type = 'MOS'\n  AND store.name IN ($store)\n  GROUP BY store.name, item.name, value\n) as a\n  WHERE item = $item\ngroup by item\n) as b\ngroup by 2;"
    }
   ]
  },
  {
   "title": "Transactions per Store",
   "type": "table",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select \"Store\", \"Week\", \"Month\" from store_transactions\nwhere \"Store\" in ([[store]])\n\n\n"
    }
   ]
  },
  {
   "title": "Stock History over time by Store",
   "type": "graph",
   "gridPos": { "h": 11, "w": 13, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT date as \"time\", store.name as metric, sum(value)\n          FROM data_values stock\n             JOIN data_value_elements store_join ON stock.uid::text = store_join.data_value_uid\n                          join data_elements store on store_join.data_element_uid = store.uid\n          WHERE stock.type='stockHistory' and store.type = 'store'\n  and $__timeFilter(\"date\")\n  and store.name in ([[store]])\n  group by 1, 2\n  order by 1, 2\n  "
    }
   ]
  },
  {
   "title": "Stock and transactions (click to show/hide)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }
  }
 ]
}