{
 "title": "Sample",
 "tags": [ "mSupply" ],
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "store",
    "label": "Store",
    "query": "select distinct name from store where disabled=false and store_mode in ('store', 'dispensary');"
   },
   {
    "name": "item",
    "label": "Item",
    "query": "select item_name from item order by item_name;"
   },
   {
    "name": "region",
    "query": "select region.description from name_category1 as region join name_category1_level2 as parent on parent.id = region.parent_id where parent.description = 'Aotearoa';"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Stock Value",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "format": "currencyUSD",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select current_date as time, sum(a.value)\nfrom aggregator a\njoin store s on a.storeid = s.id \nwhere a.dataelement='totalStockValue' and s.name in ([[store]]) \ngroup by 1;\n"
    }
   ]
  },
  {
   "title": "Months of Stock by Region",
   "type": "grafana-region-map-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\",\n  region,\n  geojson::text,\n  avg(value) AS \"value\"\nFROM region_mos\nwhere store in ([[store]])\nGROUP BY 1,2,3\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stock Status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 1, "y": 2 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select CURRENT_DATE AS \"time\", case when value = 0 then 'zero' when value > 2 then 'over' when value < 1 then 'under' else 'normal' end as metric, count(*) as count \nfrom\n(\nselect avg(value) as value\nfrom\n(\n   SELECT item.item_name AS item, mos.value\n   FROM aggregator mos\n    JOIN store ON mos.storeid = store.id \n    join item on mos.itemid = item.id\n  WHERE mos.dataelement = 'mos'\n  AND store.name IN ($store)\n  GROUP BY store.name, item.item_name, value\n) as a\n  WHERE item = $item\ngroup by item\n) as b\ngroup by 2;"
    }
   ]
  },
  {
   "title": "Stock Value by Store",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 2 },
   "format": "currencyUSD",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT CURRENT_DATE AS \"time\",\n    store.name AS \"metric\",\n    sum(stock.value) \n   FROM aggregator stock\n   join store ON stock.storeid = store.id\n  WHERE stock.dataelement = 'totalStockValue' AND store.name IN ($store)\n  group by 1, 2;"
    }
   ]
  },
  {
   "title": "Transactions per Store",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select \"store\", \"week\", \"month\" from store_transactions\nwhere \"store\" in ([[store]])\n\n\n"
    }
   ]
  },
  {
   "title": "Transactions per Store",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "select \"store\", \"week\", \"month\" from store_transactions\nwhere \"store\" in ([[store]])\n\n\n"
    }
   ]
  },
  {
   "title": "Stock History over time by Store",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT a.fulldate as \"time\", store.name as metric, sum(value)\n          FROM aggregator a\n          JOIN store on a.storeid = store.id \n          WHERE a.dataelement='stockHistory' \n            and store.disabled = false\n            and $__timeFilter(a.fulldate)\n            and store.name in ([[store]])\n  group by 1, 2\n  order by 1, 2\n"
    }
   ]
  },
  {
   "title": "Months of stock by Store",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  current_date AS \"time\",\n  store AS metric,\n  max(latitude) AS \"latitude\",\n  max(longitude) AS \"longitude\",\n  avg(value) AS \"value\"\nFROM store_mos\nWHERE\n  $__timeFilter(current_date)\nGROUP BY store,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}