{
 "title": "MOS Dashboard with Filters",
 "tags": [ "mSupply" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "multiFacility",
    "label": "Multi Facility",
    "query": "SELECT \n    NAME \nFROM \n\t$storeTableName \nWHERE \n\tLOWER(NAME) LIKE LOWER('%$facilityFilter%')\n\tAND code IN ($code)\n\tAND category1 IN ($nameCategory1)\n\tAND category1_level2 IN ($nameCategory1Level2)\n\tAND category1_level1 IN ($nameCategory1Level1)\n\tAND category2 IN ($nameCategory2)\n\tAND category3 IN ($nameCategory3)\n\tAND category4 IN ($nameCategory4)\n\tAND category5 IN ($nameCategory5)\n\tAND category6 IN ($nameCategory6)\n\tAND organisation in ($organisation)\n\tAND mode in ($mode)\n\tAND disabled in ($disabled)\n\t\n"
   },
   { "name": "facilityFilter", "label": "Facility Filter" },
   { "name": "codeStart", "label": "Code starts with" },
   {
    "name": "code",
    "label": "Code",
    "query": "SELECT code FROM $storeTableName"
   },
   {
    "name": "nameCategory1",
    "label": "Category 1",
    "query": "SELECT category1 FROM $storeTableName\nORDER BY category1 = '$nullString' desc, category1"
   },
   {
    "name": "nameCategory1Level2",
    "label": "Category 1 Level 2",
    "query": "SELECT category1_level2 FROM $storeTableName\nORDER BY category1_level2 = '$nullString' desc, category1_level2"
   },
   {
    "name": "nameCategory1Level1",
    "label": "Category 1 Level 1",
    "query": "SELECT category1_level1 FROM $storeTableName\nORDER BY category1_level1 = '$nullString' desc, category1_level1"
   },
   {
    "name": "nameCategory2",
    "label": "Category 2",
    "query": "SELECT category2 FROM $storeTableName\nORDER BY category2 = '$nullString' desc, category2"
   },
   {
    "name": "nameCategory3",
    "label": "Category 3",
    "query": "SELECT category3 FROM $storeTableName\nORDER BY category3 = '$nullString' desc, category3"
   },
   {
    "name": "nameCategory4",
    "label": "Category 4",
    "query": "SELECT category4 FROM $storeTableName\nORDER BY category4 = '$nullString' desc, category4"
   },
   {
    "name": "nameCategory5",
    "label": "Category 5",
    "query": "SELECT category5 FROM $storeTableName\nORDER BY category5 = '$nullString' desc, category5"
   },
   {
    "name": "nameCategory6",
    "label": "Category 6",
    "query": "SELECT category6 FROM $storeTableName\nORDER BY category6 = '$nullString' desc, category6"
   },
   {
    "name": "organisation",
    "label": "Organisation",
    "query": "SELECT organisation FROM $storeTableName\nORDER BY organisation = '$nullString' desc, organisation"
   },
   {
    "name": "mode",
    "label": "Mode",
    "query": "SELECT mode FROM $storeTableName"
   },
   {
    "name": "disabled",
    "label": "Disabled",
    "query": "SELECT disabled FROM $storeTableName"
   },
   {
    "name": "singleFacility",
    "label": "Single Facility",
    "query": "SELECT name FROM $storeTableName\nWHERE name in ($multiFacility)"
   },
   {
    "name": "itemCategory",
    "label": "Item Category",
    "query": "SELECT category \nFROM $itemTableName \nORDER BY category = '$nullString' DESC, category"
   },
   {
    "name": "itemCategoryLevel2",
    "label": "Item Category Level 2",
    "query": "SELECT category_level2\nFROM $itemTableName \nORDER BY category_level2 = '$nullString' DESC, category_level2"
   },
   {
    "name": "itemCategoryLevel1",
    "label": "Item Category Level 1",
    "query": "SELECT category_level1\nFROM $itemTableName \nORDER BY category_level1 = '$nullString' DESC, category_level1"
   },
   {
    "name": "itemCategory2",
    "label": "Item Category 2",
    "query": "SELECT category2\nFROM $itemTableName \nORDER BY category2 = '$nullString' DESC, category2"
   },
   {
    "name": "itemCategory3",
    "label": "Item Category 3",
    "query": "SELECT category3\nFROM $itemTableName \nORDER BY category3 = '$nullString' DESC, category3"
   },
   {
    "name": "venCategory",
    "label": "VEN",
    "query": "SELECT ven_category\nFROM $itemTableName \nORDER BY ven_category = '$nullString' DESC , ven_category DESC"
   },
   {
    "name": "stockType",
    "label": "Stock Type",
    "query": "On essential drug list, Critical stock, Normal stock, NONE"
   },
   {
    "name": "stockLevel",
    "label": "Stock Level",
    "query": "Out of Stock, Low Stock, Good Stock, Over Stock"
   },
   { "name": "itemFilter", "label": "Item Filter" },
   {
    "name": "multiItem",
    "label": "Multi Item",
    "query": "SELECT item_name\nFROM $itemTableName\nWHERE\nLOWER(item_name) LIKE LOWER( '%$itemFilter%')\nAND category IN ($itemCategory)\nAND category_level2 IN ($itemCategoryLevel2)\nAND category_level1 IN ($itemCategoryLevel1)\nAND category2 IN ($itemCategory2) \nAND category3 IN ($itemCategory3)\nAND ven_category IN ($venCategory) \nAND stock_type IN ($stockType)"
   },
   {
    "name": "singleItem",
    "label": "Single Item",
    "query": "SELECT item_name\nFROM item_categories\nWHERE item_name IN ($multiItem)\n"
   },
   { "name": "nullString", "label": "nullString", "query": "NONE" },
   { "name": "storeTableName", "label": "Store Table Name", "query": "store_categories" },
   { "name": "itemTableName", "label": "Item Table Name", "query": "item_categories" },
   {
    "name": "facilityCount",
    "label": "Count",
    "query": "SELECT \n    COUNT(name) \nFROM \n\t$storeTableName \nWHERE \n\tname in ($multiFacility)"
   },
   {
    "name": "itemCount",
    "label": "ItemCount",
    "query": "SELECT \n    COUNT(item_name) \nFROM \n\t$itemTableName \nWHERE \n\titem_name in ($multiItem)"
   },
   { "name": "sqlRestriction", "label": "SQL Restriction", "query": "1=1" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "content": "\n### Dashboard notes\n\nThe variables (above) above have been implemented to: \n- allow easy filtering/cusomisation of views for users  \n- provide maximum flexibility/generalisation while keeping the invididual panel queries as simple as possible.\n\nThere are more variables than those shown here. See `Dashboard Settings -> Variables` for full variable list.\n\n(Note: these variables require additional Postgres views `store_categories` and `item_categories` to be created)\n\nThe idea is that any possible filtering options are available via variables, but most will be preset and hidden, depending on the user.\nThis way, we can use the same Dashboard layout everywhere but simply change the (hidden) variable settings to customise for each user's requirements.\n\n\n\n"
  },
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Multi Store MOS for Single Item: $singleItem",
   "type": "grafana-worldmap-panel-msupply",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "rawSql": "select latitude, longitude, name.name as metric, case when aggregator.value is null then 0 else aggregator.value end\nfrom store join name on name.id = store.name_id \nleft join aggregator on aggregator.storeID = store.id and aggregator.itemID = (select id from item where item_name = '$singleItem') and aggregator.dataElement = 'currentMOS'\nwhere latitude <> 0 and store.name in ($multiFacility)"
    }
   ]
  },
  {
   "title": "Stock Levels for $itemCount items across $facilityCount facilities",
   "type": "msupply-horizontal-bar",
   "gridPos": { "h": 17, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "rawSql": "with\nstocklevels as\n(\n\tselect itemID,\n\tcase when value <= 3 then 1 else null end as stockLevelCritical,\n\tcase when value > 3 and value <= 6 then 1 else null end as stockLevelLow,\n\tcase when value > 6 and value <= 24 then 1 else null end as stockLevelNormal,\n\tcase when value > 24 then 1 else null end as stockLevelOverStock,\n\tcase \n\t\twhen value < 3 then 'Out of Stock'\n\t\twhen value < 6 then 'Low Stock'\n\t\twhen value < 24 then 'Good Stock'\n\t\telse 'Over Stock'\n\t\tend stockLevel\n\tfrom aggregator \n\t  join item_categories on itemid=item_categories.id \n\twhere dataElement = 'currentMOS' \n\t\tand storeID in (select id from store where name in ($multiFacility)) \n\t\tand item_categories.stock_type IN ($stockType)\n)\nselect item_name, count(*), \n\tcount(stockLevelCritical) as criticalcount, \n\tcount(stockLevelLow) as lowcount, \n\tcount(stockLevelNormal) as normalcount,\n\tcount(stockLevelOverStock) as overcount,\n\t1 as criticalthreshold,\n\t2 as lowthreshold,\n\t3 as normalthreshold,\n\t4 as overthreshold,\n\tcount(stockLevelLow) || ' facilitie/s low stock' as lowlabel,\n\tcount(stockLevelCritical) || ' facilitie/s out of stock' as criticallabel,\n\tcount(stockLevelNormal) || ' facilitie/s normal stock' as normallabel,\n\tcount(stockLevelOverStock) || ' facilitie/s over stock' as overlabel\nfrom item \nJOIN stocklevels ON item.id = itemID\n  \nwhere stocklevels.stockLevel in ($stockLevel)\nAND item_name IN ($multiItem)\ngroup by 1 \norder by item_name = '$singleItem', item_name desc"
    }
   ]
  },
  {
   "title": "Stock Status — $itemCount items across $facilityCount facilites",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "with\nstocklevels as\n(\n\tselect itemID,\n\tcase when value <= 3 then 1 else null end as stockLevelCritical,\n\tcase when value > 3 and value <= 6 then 1 else null end as stockLevelLow,\n\tcase when value > 6 and value <= 24 then 1 else null end as stockLevelNormal,\n\tcase when value > 24 then 1 else null end as stockLevelOverStock,\n\tcase \n\t\twhen value < 3 then 'Out of Stock'\n\t\twhen value < 6 then 'Low Stock'\n\t\twhen value < 24 then 'Good Stock'\n\t\telse 'Over Stock'\n\t\tend stockLevel\n\tfrom aggregator \n\t  join item_categories on itemid=item_categories.id \n\twhere dataElement = 'currentMOS' \n\t\tand storeID in (select id from store where name in ($multiFacility)) \n\t\tand item_categories.stock_type IN ($stockType)\n)\nselect item_name as \"Item\",\n  count(stockLevelCritical)  as \"Critical Stock\",\n\tcount(stockLevelLow)  as \"Low Stock\",\n\tcount(stockLevelNormal)  as \"Normal Stock\",\n\tcount(stockLevelOverStock)  as \"Over stock\"\nfrom item \n  join stocklevels on item.id=itemID\ngroup by 1 \norder by item_name"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 16, "w": 7, "x": 14, "y": 25 },
   "content": "# ☜\n\nThis panel (left) shows the same information as the above (right) graph, but in a simpler tabular form. However it is much more responsive, easily navigable, and will work with Drill-down (eventually)\n\n\n"
  },
  {
   "title": "MOS Levels for $itemCount items across 5 AMS facilities",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT * FROM crosstab(\n\t'SELECT item_name, name, value FROM aggregator \njoin store on storeid = store.id\njoin item on itemid = item.id\nwhere dataelement = ''currentMOS''\nAND name in (''Badili AMS'',''Hagen AMS'',''Kokopo AMS'',''Lae AMS'',''Wewak AMS'')\nand item_name in (''Adrenaline Injection, 1:1000, 1ml'',''Albendazole Tablets, 200mg'',''Aluminium Hydroxide Gel Compound Tablets, 500mg'',''Aminophylline Tablets, 100mg'',''Amoxycillin 500mg + Clavulanic Acid 125mg Tablets'',''Amoxycillin Capsules, 500mg'',''Amoxycillin Syrup, 125mg/5ml, 100ml'',''Amoxycillin Tablets, 250mg'',''Antibiotic Compound Eye Drops, 10ml (Gramicidin/Neomycin Sulph/Polymix B Sulph)'',''Artemether 20 mg+Lumefantrine 120mg Tablets, 15-24kg, blister 12x1'',''Artemether 20 mg+Lumefantrine 120mg Tablets, 25-34kg, blister 18x1'',''Artemether 20 mg+Lumefantrine 120mg Tablets, 35+ kg, blister 24x1'',''Artemether 20 mg+Lumefantrine 120mg Tablets, 5-14kg, blister 6x1'',''Artemether Injection, 40mg/ml in 1ml'',''Artemether Injection, 80mg/ml in 1ml'',''Artesunate Injection, 60mg/6ml, powder for injection + solvent'',''Atracurium Besylate Injection, 10mg/ml, 5ml'',''Azithromycin Tablets, 500mg'',''Bleomycin injection, 15mg in vial'',''Bupivacaine Injection, 0.5% Heavy, 4 ml '',''Bupivacaine Injection, 0.5%, 10ml '',''Calcium Gluconate Injection, 100mg/ml, 10ml'',''Calcium Sodium Edetate Injection, 200mg/ml, 5ml'',''Cefaclor Capsules, 250mg'',''Cefaclor Suspension, 125mg/5ml, 100ml'',''Ceftriaxone Injection, 1g'',''Charcoal Activated Solution, 50g/300ml'',''Chlorhexidine 1%, Chlorhexidine Gluconate (in a pourable water-miscible base)'',''Chlorhexidine Gluconate Solution, 5%, 1000ml'',''Ciprofloxacin Tablets, 250mg'',''Clotrimazole Vaginal Cream, 1%, 20g'',''Co-trimoxazole Paediatric Suspension, 40mg + 200mg, 100ml'',''Co-trimoxazole Tablets, 160mg + 800mg'',''Co-trimoxazole Tablets, 80mg + 400mg'',''Codeine Phosphate Tablets, 30mg'',''Contraceptive Injection (Medroxyprogesterone Acetate), 150mg/ml, 1ml'',''Contraceptive Oral Tablets (Ethinyloestradiol 30mcg&Levonorgestrel 150mcg),Pk/28'',''Contraceptive Oral Tablets (Levonorgestrel 30mcg),Pkt/28'',''Dexamethasone Phosphate Injection, 4mg in 1ml'',''Diazepam Injection, 5mg/ml, 2ml'',''Diclofenac Tablets, 25mg'',''Dihydroartemisinin-piperaquine Tablets 20mg+160mg'',''Dihydroartemisinin-piperaquine Tablets 40mg+320mg'',''Docusate with Senna Tablets, 50mg/8mg'',''Dopamine Injection, 40mg/ml, 5ml'',''Doxycycline Tablets, 100mg'',''Enalapril Tablets, 10mg'',''Enalapril Tablets, 5mg'',''Ergometrine Maleate Injection, 0.5mg in 1ml'',''Erythromycin  Suspension, 125mg/5ml, 100ml'',''Erythromycin Tablets, 250mg'',''Fentanyl Citrate Injection, 50mcg/ml,  2ml'',''Ferrous Sulphate Tablets, 60mg'',''Flucloxacillin Capsule, 500mg'',''Flucloxacillin Capsules, 250mg'',''Flucloxacillin Injection, 500mg in vial'',''Flucloxacillin Suspension, 125mg/5ml, 100ml'',''Folic Acid Tablets, 5mg'',''Frusemide Injection, 20mg in 2ml'',''Frusemide Tablets, 40mg'',''Gamma Benzene Hexachloride, Lindane 1%, Bot/2L'',''Gentamicin Injection, 80mg in 2ml'',''Gentamicin Injection, Paediatric, 20mg in 2ml'',''Gliclazide Tablets 80mg'',''Hydrocortisone Sodium Succinate Injection, 100mg with diluent'',''Hyoscine Butylbromide Injection, 20mg in 1ml'',''Hyoscine Butylbromide Tablets, 10mg'',''IV Fluid, Dextrose Injection, 50%, 50ml'',''IV Fluid, Dextrose, 10%, 500ml'',''IV Fluid, Dextrose, 2.5% in Half Strength Darrow''''s Solution, 500ml'',''IV Fluid, Dextrose, 4.3% in 0.18% Sodium Chloride, 1L'',''IV Fluid, Dextrose, 5%, 1L'',''IV Fluid, Sodium Chloride Injection, 0.9%, 10ml'',''IV Fluid, Sodium Chloride Injection, 0.9%, 1L'',''IV Fluid, Sodium Lactate, Compound Solution, Hartmann''''s Solution, 1L'',''Irrigation Solution, Sodium Chloride, 0.9%, 500ml with screw top'',''Isoprenaline Injection, 1:5000, 1ml'',''Levodopa 100mg + Carbidopa 10mg Tablets'',''Lignocaine 1% with Adrenaline 1:100,000'',''Lignocaine 2% with Adrenaline 1:80,000'',''Lignocaine Injection, Plain, 1%, 20ml'',''Lignocaine Injection, Plain, 2%, 20ml'',''Lignocaine, 100mg/5ml (Xylocard 100)'',''Magnesium Sulphate Injection, 500mg/ml, 10ml'',''Metformin Tablets, 500mg'',''Methyldopa Tablets, 250mg'',''Metoclopramide Injection, 5 mg/ml, 2ml'',''Metoclopramide Tablets, 10mg'',''Metronidazole I.V. Injection, 500mg/100ml'',''Metronidazole Suppository, 500mg, Box/10'',''Metronidazole Tablets, 200mg'',''Misoprostol Tablets, 200mcg'',''Morphine Sulphate Injection, 10mg/ml'',''Morphine Sulphate, SR Tablets, (MS Contin)  30mg'',''Multivitamin, Liquid, 50ml'',''Nystatin Oral Suspension, 100,000 IU/ml, 50ml'',''Omeprazole Tablets, 20mg'',''Oral Rehydration Solution, Powder Form, (O.R.S.), Sachet'',''Oxytocin Injection, 10 IU in 1ml'',''Paracetamol Elixir, 120mg/5ml, 100ml'',''Paracetamol Tablets, 500mg'',''Paraldehyde I.M. Injection, 1g/ml, 5ml'',''Penicillin, Benzyl Injection, 600mg (1 million IU)'',''Pethidine Injection, 50mg/ml, in 1ml'',''Phenytoin Sodium Capsules/Tablets, 100mg'',''Phenytoin Sodium Paediatric Suspension, 30mg/5ml, 500ml'',''Phytomenadione Injection, 1mg/ml, 1ml'',''Potassium Chloride Injection, (10ml), 2g in 8ml'',''Potassium Chloride SR Tablets, 600mg'',''Potassium Permanganate, 1:10,000'',''Povidone Iodine Solution, 10%, 500ml'',''Povidone Iodine Surgical Scrub Solution, 7.5%, 500ml'',''Prednisolone Tablets, 5mg'',''Primaquine Tablets, 7.5mg'',''Probenecid Tablets, 500mg'',''Promethazine Tablets, 25mg'',''Quinine Dihydrochloride Injection, 600mg in 2ml'',''Quinine Tablets, 300mg'',''Ranitidine Hydrochloride Tablets, 150mg'',''Salbutamol Aerosol, 100mcg, 200 doses, Complete'',''Salbutamol Injection, 0.5mg in 1ml'',''Salbutamol Nebulizer Ampoules, 2.5mg/2.5ml'',''Salbutamol Respirator Solution, 5mg/ml, 30ml'',''Salbutamol Tablets, 4mg'',''Silver Sulfadiazine Cream, 1%, 500g'',''Skin Swab, Alcohol, Sterile, Pkt/100'',''Soda Lime, 3kg          '',''Sulphadoxine 500mg + Pyrimethamine 25mg Tablets'',''Tetracycline Eye Ointment, 1%, 5g'',''Tinidazole Tablets,  500mg'',''Tuberculin, Diluted,  5 IU/0.1ml, 10ml'',''Vitamin A Concentrate Capsules, 100,000 IU'',''Vitamin C (Ascorbic Acid) Tablets, 50mg'',''Warfarin Sodium Tablets, 5mg'',''Water for Injection, 10ml'',''Zinc Sulphate Tablets, 20 mg'')\nORDER by 1, 2'\n)\nAS\n(\"Item\" character varying,\n\"Badili AMS\" float,\n\"Hagen AMS\" float,\n\"Kokopo AMS\" float,\n\"Lae AMS\" float,\n\"Wewak AMS\" float\n) "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 15, "y": 41 },
   "content": "# ☜\n\nThis panel (left) shows stock information per store. However, the query is a complicated CrossTab query, so these store names are hard-coded currently. Not sure how we'd go about creating it so the columns update dynamically."
  },
  { "title": "Single Facility/Item", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Multi Store MOS for Single Item: $singleItem",
   "type": "msupply-horizontal-bar",
   "gridPos": { "h": 18, "w": 11, "x": 0, "y": 57 },
   "targets": [
    {
     "rawSql": "select name.name as storeName, case when aggregator.value is null then 0 else round(aggregator.value::numeric, 1) end as mos,\ncase\nwhen value < 3 then 1\nwhen value < 6 then 2\nwhen value < 24 then 3\nelse 4\nend as threshold\nfrom store join name on name.id = store.name_id \nleft join aggregator on aggregator.storeID = store.id and aggregator.itemID = (select id from item where item_name = '$singleItem') and aggregator.dataElement = 'currentMOS'\nwhere latitude <> 0 and store.name in ($multiFacility)"
    }
   ]
  },
  {
   "title": "Multi Item MOS for Single Store: $singleFacility",
   "type": "msupply-horizontal-bar",
   "gridPos": { "h": 18, "w": 11, "x": 11, "y": 57 },
   "targets": [
    {
     "rawSql": "select item_name, \ncase when value > 48 then 48 else ROUND(value::numeric, 1) end as mos,\nstockLevelNumber as threshold, \"stockLevel\" from \n\titem left join (\n\tselect itemID, value,\n\tcase\n\twhen value < 3 then 1\n\twhen value < 6 then 2\n\twhen value < 24 then 3\n\telse 4\n\tend as stockLevelNumber,\n\tcase \n\twhen value < 3 then 'Out of Stock'\n\twhen value < 6 then 'Low Stock'\n\twhen value < 24 then 'Good Stock'\n\telse 'Over Stock'\n\tend \"stockLevel\"\n\tfrom aggregator \n\twhere dataElement = 'currentMOS' and storeID = (select id from store where name ='$singleFacility')) \n\tas sl on sl.itemID = item.id\n\twhere \"stockLevel\" in ($stockLevel) \nand item_name in ($multiItem)  \norder by item_name = '$singleItem', item_name desc"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 75 },
   "content": "The same information as the above, but using different displays (Bar Gauge). \n\nThe bar gauge panels are vastly superior when displaying only a few items (<20) but quickly become unwieldy.\n\n\n\n"
  },
  {
   "title": "Multi-Store MOS for Single Item: $singleItem",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 77 },
   "targets": [
    {
     "rawSql": "SELECT store.name as \"Store\", value as \"MOS\" FROM public.aggregator\nJOIN store ON storeid = store.id\nJOIN item on itemid = item.id\nWHERE dataelement = 'currentMOS'\nAND name IN ($multiFacility)\nAND item_name = '$singleItem'"
    }
   ]
  },
  {
   "title": "Multi-Store MOS for Single Facility: $singleFacility",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 77 },
   "targets": [
    {
     "rawSql": "with stocklevels as\n(\nSELECT \n    item_name AS \"Item\", \n\tVALUE AS \"MOS\", \n\tCASE WHEN VALUE < 3 THEN 'Out of Stock' WHEN VALUE < 6 THEN 'Low Stock' WHEN VALUE < 24 THEN 'Good Stock' ELSE 'Over Stock' END as stocklevel \nFROM \n\taggregator \n\tJOIN store ON storeid = store.id \n\tJOIN item ON itemid = item.id \nWHERE \n\tdataelement = 'currentMOS' \n\tAND NAME = '$singleFacility' \n\tAND item_name IN ($multiItem)\n)\nselect \"Item\", \"MOS\"\nfrom stocklevels\nWHERE stocklevel IN ($stockLevel)\nORDER BY \n\t\"Item\" = '$singleItem' DESC, \n\t\"Item\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 22, "x": 0, "y": 91 },
   "content": "Same again, but using a histogram (Facilities) and a simple table (Items).\n\nThe histogram becomes useless when the columns get too close together. The table is quite effective, clearly shows all information, but is not as visually impressive as the (sparse) bar gauges (above).\n\n\n"
  },
  {
   "title": "Multi-Store MOS for Single Item: $singleItem",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT current_timestamp as time, store.name as metric, value as \"MOS\" FROM public.aggregator\nJOIN store ON storeid = store.id\nJOIN item on itemid = item.id\nWHERE dataelement = 'currentMOS'\nAND name IN ($multiFacility)\nAND item_name = '$singleItem'"
    }
   ]
  },
  {
   "title": "MOS ($stockLevel) for Single Facility: $singleFacility",
   "type": "table",
   "gridPos": { "h": 14, "w": 11, "x": 11, "y": 93 },
   "targets": [
    {
     "rawSql": "with stocklevels as\n(\nSELECT \n    item_name AS \"Item\", \n\tVALUE AS \"MOS\", \n\tCASE WHEN VALUE < 3 THEN 'Out of Stock' WHEN VALUE < 6 THEN 'Low Stock' WHEN VALUE < 24 THEN 'Good Stock' ELSE 'Over Stock' END as stocklevel \nFROM \n\taggregator \n\tJOIN store ON storeid = store.id \n\tJOIN item ON itemid = item.id \nWHERE \n\tdataelement = 'currentMOS' \n\tAND NAME = '$singleFacility' \n\tAND item_name IN ($multiItem)\n)\nselect \"Item\", \"MOS\"\nfrom stocklevels\nWHERE stocklevel IN ($stockLevel)\nORDER BY \n\t\"Item\" = '$singleItem' DESC, \n\t\"Item\""
    }
   ]
  }
 ]
}